# StickySurvival configuration

# Time units are in SECONDS, not ticks.

# Database credentials
db:
  database: minecraft
  host: localhost
  port: 5432
  username: AzureDiamond
  password: hunter2

# Where players will spawn in the lobby. If set to "world spawn", this will be the world's actual spawn point.
lobby spawn: world spawn

# How long players will wait for the game to start after the minimum number of players is reached.
countdown: 10

# How long, after a game ends, until all players are automatically removed from the world.
results time: 5

# How long a player must wait between attempts to join games.
join cooldown: 10

# How long players will be able to roam without taking damage (free roam).
no damage time: 30

# Amount to reward players for winning.
reward: 100

random chest: # (care package)
  interval: 300 # Time interval in between random chest drops.
  min items: 1 # Minimum amount of items that can be in a random chest. The bonus loot is used.
  max items: 8 # Maximum amount

tracking compass:
  name: '&aTracking Compass' # Name of tracking compass
  lore: [ '&3&oTrack down and finish', '&3&ooff your enemies!' ] # Lore for tracking compass
  message: '&eNearest player: &f%s&e at &f%d&e, &f%d&e, &f%d'
  basic loot weight: 1 # Weight of compass in chest loot.
  bonus loot weight: 1 # Weight of compass in bonus loot.

# Blocks that can be broken; they will not drop anything
breakable blocks:
  - GRASS
  - TALL_GRASS
  - FERN
  - LARGE_FERN
  - WITHER_ROSE
  - POPPY
  - DANDELION
  - COBWEB

# Containers that will use the bonus loot instead of the basic loot
# As a shortcut, "shulker_boxes" will match all 17 shulker box types
bonus containers:
  - TRAPPED_CHEST
  - BARREL
  - SHULKER_BOXES

# Kits: can specify armor, items, and potion effects
kits:
  example:
    helmet:
      item: LEATHER_HELMET
    chestplate:
      item: LEATHER_CHESTPLATE
    leggings:
      item: LEATHER_LEGGINGS
    boots:
      item: LEATHER_BOOTS
    effects:
      - type: SPEED
        duration: forever
        amplifier: 0
    items:
      - item: BREAD
        amount: 2

# More weight -> greater chance of item, default weight is 1
# These items are not designed to be a good set of items for a game, they are only here as examples.
basic loot:
  min: 1 # Minimum # of items that can be generated from this loot table
  max: 2 # Maximum
  entries:
    # A simple item
    - item: APPLE
    # This item is eight times as likely to appear
    - item: STONE_SWORD
      weight: 8
    # Custom name with a color code
    - item: FLINT_AND_STEEL
      name: '&eLighter'
    # This item will appear in groups of three
    - item: COOKIE
      amount: 3
    # Entries can have the same item with different parameters
    - item: MELON_SLICE
      amount: 2
    - item: MELON_SLICE
      amount: 5
    # This sword has Sharpness I
    - item: IRON_SWORD
      enchantments:
        DAMAGE_ALL: 1
    # This potion has a custom color and gives 3 minutes of speed
    - item: SPLASH_POTION
      color: 0x803EFF
      effects:
        - type: SPEED
          duration: 180
          amplifier: 0
    # This potion has an effect that lasts virtually forever
    - item: SPLASH_POTION
      color: 0x00FF00
      effects:
        - type: POISON
          duration: forever
          amplifier: 0
    # Leather can be dyed
    - item: LEATHER_CHESTPLATE
      color: 0x0000FF
    # Colors can be dye names
    - item: LEATHER_BOOTS
      color: blue
    # Items can have lore
    - item: IRON_SWORD
      name: Judgement Day
      lore:
        - A holy blade responsible
        - for sending the undead
        - back to the underworld.

# Loot for bonus chests and care packages
bonus loot:
  min: 1
  max: 1
  entries:
    - item: DIAMOND_SWORD
